### ISSUE TITLE
add http  path to config

### ISSUE THREAD

**Issue by mouhsinelonly** [rynocouse/laravel-elixir-compass#11]
after compilation "public/" is added to the path of generated images and fonts , to avoid this ,pelase add compass option to config

http_generated_images_path

http_generated_javascript_path

http_generated_fonts_path

**Comment by JoeCianflone** [comment]
@mouhsinelonly looks like gulp-compass only supports `generated_images_path` so I'll add that in along with a couple of other env vars.  I'll need to do some testing but should have this up in [the new repo](https://github.com/JoeCianflone/laravel-elixir-sass-compass) this week.
