### ISSUE TITLE
Compiles to within app, but also duplicate structure OUTSIDE my app folder?

### ISSUE THREAD

**Issue by DuGi** [rynocouse/laravel-elixir-compass#5]
Hi,

I'm not sure if this is actually an issue, if not feel free to welcome it. Just didn't where else to "report" it.

I'm a bit new to all this Elixir thing. But I'm a huge fan of Compass. So thank you very much for this contribution!

My issue is when I'm compiling my SCSS inside Elixir. I have the following structure on my VPS:
`/home/morten/sites/laravel-app/`

When I run my `gulp` it looks like it's compiling correct. Which it also actually does. It creates my files in my desired directory:
`/home/morten/sites/laravel-app/public/css/*.css``

But for some reason it ALSO creates the same structure `public/css/*.css` inside my `/home/morten/sites/`folder.

So when I `gulp` I end up with the following structure:
`/home/morten/sites/laravel-app/public/css/*.css`
`/home/morten/sites/public/css/*.css`

The reason to why I suspect it is an issue with your extension is because it's only the files that gets "handled" by your app, that ends up in the weird "second structure" outside my Laravel app folder. All the concatinations, JS and versioning does not.

My `gulpfile.js` looks likes this:
```
var elixir = require('laravel-elixir');

// Elixir extensions
require('laravel-elixir-compass');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

elixir(function(mix) {
	 mix.compass([
			'base.scss',
			'bootstrap.scss',
			'font-awesome.scss'
		])
		.styles([
			'bootstrap.css',
			'font-awesome.css',
			'base.css'
		], 'public/css', 'public/css/all.min.css')
		.publish('jquery/dist/jquery.min.js', 'public/js/jquery.js')
		.publish('jquery-ui/jquery-ui.min.js', 'public/js/jquery-ui.js')
		.publish('bootstrap-sass-official/assets/javascripts/bootstrap.js', 'public/js/bootstrap.js')
		.scripts([
			'jquery.js',
			'jquery-ui.js',
			'bootstrap.js'
		], 'public/js', 'public/js/all.min.js')
		.version([
			'public/css/all.min.css',
			'public/js/all.min.js'
		]);
});
```

I hope my explaination of my issue make sense. If not please ask all the question you desire. And if you need more data, like version numbers etc. - don't hesitate to ask.

Again thank you for your work and contribution :)

Regards,
Morten

**Comment by JoeCianflone** [comment]
This is fixed in the new repo, check out the readme for more information.  Thanks
